[project]
name = "adk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.70",
    "fastapi==0.118.3",
    "google-adk>=1.18.0",
    "litellm>=1.79.3",
    "pydantic>=2.11.1,<3",
]
