[project]
name = "analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipython>=9.8.0",
    "matplotlib>=3.10.8",
    "matplotlib-venn>=1.1.2",
    "pandas>=2.3.3",
    "pudb>=2025.1.3",
    "seaborn>=0.13.2",
]